version: '3.3'
services:
  node:
    build: .
    ports:
      - "8101:3000"
    expose:
      - "3000"
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASES: userDB
      MYSQL_USER: root
      MYSQL_PASSWORD: Ff_0828953195 
      MYSQL_ROOT_PASSWORD: Ff_0828953195
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/:/var/lib/mysql
    expose:
      - "3306"
